apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mystira-chain

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: mystira-chain
  app.kubernetes.io/part-of: mystira
  app.kubernetes.io/component: blockchain

images:
  - name: mystira/chain
    newTag: latest
