apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mys-chain

resources:
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mys-chain
  app.kubernetes.io/part-of: mys
  app.kubernetes.io/component: blockchain

images:
  - name: mysprodacr.azurecr.io/chain
    newTag: latest
