apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mys-chain

resources:
  - deployment.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mys-chain
      app.kubernetes.io/part-of: mys
      app.kubernetes.io/component: blockchain
    includeSelectors: false

images:
  - name: myssharedacr.azurecr.io/chain
    newTag: v0.0.0  # Replace with actual version/commit SHA via CI/CD pipeline
