apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mys-dev

resources:
  - ../../base/chain
  - ../../base/publisher
  - ../../base/story-generator
  - ../../base/cert-manager

commonLabels:
  environment: dev

patches:
  - target:
      kind: Ingress
      name: mystira-publisher-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "dev.publisher.mystira.app"
      - op: replace
        path: /spec/rules/0/host
        value: "dev.publisher.mystira.app"
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: "letsencrypt-staging"
  - target:
      kind: Ingress
      name: mystira-chain-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "dev.chain.mystira.app"
      - op: replace
        path: /spec/rules/0/host
        value: "dev.chain.mystira.app"
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: "letsencrypt-staging"
  - target:
      kind: StatefulSet
      name: mys-chain
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"
      - op: remove
        path: /spec/template/spec/nodeSelector
      - op: remove
        path: /spec/template/spec/tolerations
  - target:
      kind: Deployment
      name: mys-publisher
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: remove
        path: /spec/template/spec/nodeSelector
  - target:
      kind: ConfigMap
      name: mys-publisher-config
    patch: |-
      - op: replace
        path: /data/key_vault_url
        value: "https://mys-dev-mystira-kv-san.vault.azure.net/"
  - target:
      kind: Deployment
      name: mys-story-generator
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
  - target:
      kind: ConfigMap
      name: mys-story-generator-config
    patch: |-
      - op: replace
        path: /data/key_vault_url
        value: "https://mys-dev-mystira-kv-san.vault.azure.net/"

images:
  - name: mysprodacr.azurecr.io/chain
    newTag: dev
  - name: mysprodacr.azurecr.io/publisher
    newTag: dev
  - name: mysprodacr.azurecr.io/story-generator
    newTag: dev
