apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mystira

resources:
  - namespace.yaml
  - service-accounts.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: mystira
    includeSelectors: true
