apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mys-admin-api-ingress
  labels:
    app: mystira-admin-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin-api.mystira.app
      secretName: mystira-admin-api-tls
  rules:
    - host: admin-api.mystira.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mystira-admin-api
                port:
                  number: 8080
