apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mys-admin-api

resources:
  - deployment.yaml
  - ingress.yaml
  - network-policy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mys-admin-api
      app.kubernetes.io/part-of: mys
      app.kubernetes.io/component: admin-api
    includeSelectors: true

images:
  - name: myssharedacr.azurecr.io/admin-api
    newTag: v0.0.0  # Replace with actual version/commit SHA via CI/CD pipeline
