apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mys-story-generator

resources:
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mys-story-generator
  app.kubernetes.io/part-of: mys
  app.kubernetes.io/component: story-generator

images:
  - name: myssharedacr.azurecr.io/story-generator
    newTag: v0.0.0  # Replace with actual version/commit SHA via CI/CD pipeline
