apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mystira-prod

resources:
  - ../../base/chain
  - ../../base/publisher

commonLabels:
  environment: prod

patches:
  - target:
      kind: StatefulSet
      name: mystira-chain
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "4Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "8Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "4000m"
  - target:
      kind: Deployment
      name: mystira-publisher
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
  - target:
      kind: HorizontalPodAutoscaler
      name: mystira-publisher-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 20

images:
  - name: mystira/chain
    newName: mystira/chain
    newTag: stable
  - name: mystira/publisher
    newName: mystira/publisher
    newTag: stable
