apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mystira-prod

resources:
  - ../../base/chain
  - ../../base/publisher
  - ../../base/cert-manager

commonLabels:
  environment: prod

patches:
  - target:
      kind: StatefulSet
      name: mystira-chain
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "4Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "8Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "1000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "4000m"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: "500Gi"
  - target:
      kind: Deployment
      name: mystira-publisher
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
  - target:
      kind: HorizontalPodAutoscaler
      name: mystira-publisher-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 20
  - target:
      kind: ConfigMap
      name: mystira-publisher-config
    patch: |-
      - op: replace
        path: /data/key_vault_url
        value: "https://mystira-pub-prod-kv.vault.azure.net/"

images:
  - name: mystiraacr.azurecr.io/chain
    newName: mystiraprodacr.azurecr.io/chain
    newTag: stable
  - name: mystiraacr.azurecr.io/publisher
    newName: mystiraprodacr.azurecr.io/publisher
    newTag: stable
