apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mys-admin-ui

resources:
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mys-admin-ui
  app.kubernetes.io/part-of: mys
  app.kubernetes.io/component: admin-ui

images:
  - name: myssharedacr.azurecr.io/admin-ui
    newTag: latest
