apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mystira-staging

resources:
  - ../../base/chain
  - ../../base/publisher

commonLabels:
  environment: staging

patches:
  - target:
      kind: StatefulSet
      name: mystira-chain
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: remove
        path: /spec/template/spec/nodeSelector
      - op: remove
        path: /spec/template/spec/tolerations
  - target:
      kind: Deployment
      name: mystira-publisher
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: remove
        path: /spec/template/spec/nodeSelector
  - target:
      kind: ConfigMap
      name: mystira-publisher-config
    patch: |-
      - op: replace
        path: /data/key_vault_url
        value: "https://mystira-pub-staging-kv.vault.azure.net/"

images:
  - name: mystiraacr.azurecr.io/chain
    newName: mystirastagingacr.azurecr.io/chain
    newTag: staging
  - name: mystiraacr.azurecr.io/publisher
    newName: mystirastagingacr.azurecr.io/publisher
    newTag: staging
