apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mystira-publisher

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: mystira-publisher
  app.kubernetes.io/part-of: mystira
  app.kubernetes.io/component: publisher

images:
  - name: mystiraacr.azurecr.io/publisher
    newTag: latest
