apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mys-publisher

resources:
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mys-publisher
  app.kubernetes.io/part-of: mys
  app.kubernetes.io/component: publisher

images:
  - name: myssharedacr.azurecr.io/publisher
    newTag: latest
