apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mystira-cert-manager

resources:
  - cluster-issuer.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/part-of: mystira
    includeSelectors: true
